name: Bug report
description: File a bug report to help us improve cc-worktree-squad
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS and Node.js version
      placeholder: macOS 14, Node 20.11.1
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command used
      placeholder: ccws spawn bugfix-auth --base main
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error output / logs
      render: shell
