name: Feature request
description: Suggest an idea for cc-worktree-squad
title: "[Feature] "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain point does this feature address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should this work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What did you try already?
